### ISSUE TITLE
PostCSS config export mismatch between TS definition and CommonJS in v3.8.4

### ISSUE THREAD

**Issue by malinindev** [reshaped-ui/reshaped#480]
I have a following code:

```js
const path = require('path')
const { getConfig } = require('reshaped/config/postcss')

module.exports = getConfig({
  themeMediaCSSPath: path.resolve(__dirname, 'src/styles/media.css'),
})

```

After updating from reshaped 3.8.3 to 3.8.4, PostCSS config import fails with `TypeError: getConfig is not a function

When I open the type definition (postcss.d.ts in reshaped sources), I see

```ts
export declare const config: {
    plugins: {
        "@csstools/postcss-global-data": {
            files: string[];
        };
        "postcss-custom-media": {};
        cssnano: {
            preset: (string | {
                calc: boolean;
            })[];
        };
    };
};
export declare const getConfig: (options: {
    themeMediaCSSPath: string;
}) => {
    plugins: {
        "@csstools/postcss-global-data": {
            files: string[];
        };
        "postcss-custom-media": {};
        cssnano: {
            preset: (string | {
                calc: boolean;
            })[];
        };
    };
};
```

But the actual CommonJS implementation:

```js
// ...
exports.default = getConfig;  // default export, not named export
```

**Expected (based on .d.ts):**
```javascript
const { getConfig } = require('reshaped/config/postcss')  // fails
```

**Actual workaround needed:**
```javascript
const { default: getConfig } = require('reshaped/config/postcss')  // works
```

## Fix Needed
Either:
- Update `.d.ts` to match `.cjs` implementation with `export default`
- Or update `.cjs` to export named export: `exports.getConfig = getConfig`

**Comment by blvdmitry** [comment]
Thanks for the heads-up, fixed in 3.8.5
